---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude:
    - DataMapper::Relation::Header::Attribute#self.build
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
    - DataMapper::Relation::Graph::Edge#join_relation
    - DataMapper::Relation::Header::Attribute#initialize
    - DataMapper::Relationship::Builder::Has#self.extract_min_max
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude: []
  max_calls: 1
  allow_calls:
    - 'node_map' # DataMapper::Support::Graphviz#node_map
FeatureEnvy:
  enabled: true
  exclude:
    - DataMapper::AttributeSet#dump
    - DataMapper::AttributeSet#load
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#register_base_relation
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#registered_relation
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#registered_relation
    - DataMapper::Mapper::Registry#relation_map
    - DataMapper::Relation::Graph::Node::NameSet#name
    - DataMapper::Relation::Graph::Node::NameSet#via_relationship
    - DataMapper::Relation::Header#renamed_attribute_index
    - DataMapper::Relation::Header::JoinStrategy#current_name
    - DataMapper::Relation::Header::JoinStrategy#joined_entries
    - DataMapper::Relation::Header::JoinStrategy#with_new_index_entries
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
    - DataMapper::Relation::Graph::Connector#initialize
    - DataMapper::Relationship#initialize
    - DataMapper::Relationship::Builder::BelongsTo#self.build
    - DataMapper::Relationship::Builder::Has#self.build
  max_params: 3
LongYieldList:
  enabled: true
  exclude:
    - DataMapper::Relation::Header::AttributeIndex#with_new_entries
    - DataMapper::Relation::Header::JoinStrategy#with_new_index_entries
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#finalize_edges
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#finalize_relationships
    - DataMapper::Relation::Graph::Node#order
    - DataMapper::Relation::Header::AttributeIndex#renamed_attributes
    - DataMapper::Relation::Header::AttributeIndex#renamed_relations
    - DataMapper::Relation::Header::JoinStrategy#join_key_entries
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude:
    - DataMapper::Mapper::Builder#self.create
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
    - DataMapper::Attribute
    - DataMapper::Environment
    - DataMapper::Finalizer
    - DataMapper::Relation::Graph
    - DataMapper::Relation::Graph::Connector
    - DataMapper::Relation::Graph::Edge
    - DataMapper::Relation::Graph::Node::Name
    - DataMapper::Relation::Header
    - DataMapper::Relation::Mapper
    - DataMapper::Relation::Mapper::Builder
    - DataMapper::Relationship
    - DataMapper::Relationship::Iterator::Tuples
    - DataMapper::Relationship::ViaDefinition
    - DataMapper::Support::Graphviz
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
    - DataMapper::Attribute
    - DataMapper::Environment
    - DataMapper::Finalizer
    - DataMapper::Relation::Graph
    - DataMapper::Relation::Graph::Connector
    - DataMapper::Relation::Graph::Connector::Builder
    - DataMapper::Relation::Graph::Edge
    - DataMapper::Relation::Graph::Node::Name
    - DataMapper::Relation::Graph::Node::NameSet
    - DataMapper::Relation::Header
    - DataMapper::Relation::Mapper
    - DataMapper::Relation::Mapper::Builder
    - DataMapper::Relationship
    - DataMapper::Relationship::Iterator::Tuples
    - DataMapper::Relationship::ViaDefinition
    - DataMapper::Support::Graphviz
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
    - DataMapper::Attribute#self.build
    - DataMapper::Attribute::EmbeddedValue#finalize
    - DataMapper::AttributeSet#each
    - DataMapper::AttributeSet#merge
    - DataMapper::AttributeSet#remap
    - DataMapper::Environment#build
    - DataMapper::Environment#finalize
    - DataMapper::Finalizer#run
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#register_base_relation
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#registered_node
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#registered_relation
    - DataMapper::Finalizer::BaseRelationMappersFinalizer#run
    - DataMapper::Finalizer::RelationshipMappersFinalizer#finalize_relationship_mappers
    - DataMapper::Finalizer::RelationshipMappersFinalizer#run
    - DataMapper::Mapper#each
    - DataMapper::Mapper#self.from
    - DataMapper::Mapper#self.map
    - DataMapper::Mapper::Builder#self.create
    - DataMapper::Mapper::Builder#self.define_for
    - DataMapper::Mapper::Builder#self.map_attribute
    - DataMapper::Mapper::Registry#each
    - DataMapper::Model#self.included
    - DataMapper::Options#add_accepted_option
    - DataMapper::Options#accept_options
    - DataMapper::Options#define_option_method
    - DataMapper::Query#each
    - DataMapper::Relation::Graph#freeze
    - DataMapper::Relation::Graph::Connector::Builder#add_edge
    - DataMapper::Relation::Graph::Connector::Builder#add_node
    - DataMapper::Relation::Graph::Edge#join_relation
    - DataMapper::Relation::Graph::Node#each
    - DataMapper::Relation::Graph::Node#join
    - DataMapper::Relation::Graph::Node#rename
    - DataMapper::Relation::Graph::Node::NameSet#each
    - DataMapper::Relation::Graph::Node::NameSet#rel_map
    - DataMapper::Relation::Header#each
    - DataMapper::Relation::Header#join
    - DataMapper::Relation::Header#self.build
    - DataMapper::Relation::Header::AttributeIndex#aliases
    - DataMapper::Relation::Header::AttributeIndex#renamed_relations
    - DataMapper::Relation::Header::AttributeIndex#self.initial_entries
    - DataMapper::Relation::Header::RelationIndex#aliases
    - DataMapper::Relation::Mapper#one
    - DataMapper::Relation::Mapper#order
    - DataMapper::Relation::Mapper#self.belongs_to
    - DataMapper::Relation::Mapper#self.from
    - DataMapper::Relation::Mapper#self.has
    - DataMapper::Relation::Mapper#self.key
    - DataMapper::Relation::Mapper::Builder#build
    - DataMapper::Relation::Mapper::RelationshipSet#each
    - DataMapper::Relationship#finalize
    - DataMapper::Relationship#finalize_join_definition
    - DataMapper::Relationship::Builder::Has#self.build
    - DataMapper::Relationship::Builder::Has#self.extract_min_max
    - DataMapper::Relationship::Iterator#each
    - DataMapper::Relationship::Iterator::Tuples#parent_base_tuple
    - DataMapper::Relationship::JoinDefinition#each
    - DataMapper::Relationship::ManyToMany#finalize
    - DataMapper::Relationship::OneToOne#finalize
    - DataMapper::Support::Graphviz#add_connectors
    - DataMapper::Support::Graphviz#add_edges
    - DataMapper::Support::Graphviz#add_nodes
    - DataMapper::Support::Graphviz#build
    - DataMapper::Utils#self.extract_options
    - DataMapper::Utils#self.extract_type
  max_statements: 2
UncommunicativeMethodName:
  enabled: true
  exclude:
    - 'n'  # typically used to denote infinity in DM code
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude:
    - Axiom::Adapter::Sqlite3
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude:
    - 'r' # typically used for 'relation' in blocks
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
    - DataMapper::Relation::Graph::Node::NameSet#via_relationship
    - DataMapper::Relation::Header#renamed_attribute_index
    - DataMapper::Relation::Header::AttributeIndex#new_attribute
    - DataMapper::Relation::Header::JoinStrategy#current_name
    - DataMapper::Relation::Header::JoinStrategy#joined_entries
    - DataMapper::Relation::Header::JoinStrategy#with_new_index_entries
  max_helper_calls: 0

