---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude:
    - Rom::Relation::Header::Attribute#self.build
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
    - Rom::Relation::Graph::Edge#join_relation
    - Rom::Relation::Header::Attribute#initialize
    - Rom::Relationship::Builder::Has#self.extract_min_max
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude: []
  max_calls: 1
  allow_calls:
    - 'node_map' # Rom::Support::Graphviz#node_map
FeatureEnvy:
  enabled: true
  exclude:
    - Rom::AttributeSet#dump
    - Rom::AttributeSet#load
    - Rom::Finalizer::BaseRelationMappersFinalizer#register_base_relation
    - Rom::Finalizer::BaseRelationMappersFinalizer#registered_relation
    - Rom::Finalizer::BaseRelationMappersFinalizer#registered_relation
    - Rom::Mapper::Registry#relation_map
    - Rom::Relation::Graph::Node::NameSet#name
    - Rom::Relation::Graph::Node::NameSet#via_relationship
    - Rom::Relation::Header#renamed_attribute_index
    - Rom::Relation::Header::JoinStrategy#current_name
    - Rom::Relation::Header::JoinStrategy#joined_entries
    - Rom::Relation::Header::JoinStrategy#with_new_index_entries
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
    - Rom::Relation::Graph::Connector#initialize
    - Rom::Relationship#initialize
    - Rom::Relationship::Builder::BelongsTo#self.build
    - Rom::Relationship::Builder::Has#self.build
  max_params: 3
LongYieldList:
  enabled: true
  exclude:
    - Rom::Relation::Header::AttributeIndex#with_new_entries
    - Rom::Relation::Header::JoinStrategy#with_new_index_entries
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
    - Rom::Finalizer::BaseRelationMappersFinalizer#finalize_edges
    - Rom::Finalizer::BaseRelationMappersFinalizer#finalize_relationships
    - Rom::Relation::Graph::Node#order
    - Rom::Relation::Header::AttributeIndex#renamed_attributes
    - Rom::Relation::Header::AttributeIndex#renamed_relations
    - Rom::Relation::Header::JoinStrategy#join_key_entries
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude:
    - Rom::Mapper::Builder#self.create
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
    - Rom::Attribute
    - Rom::Environment
    - Rom::Finalizer
    - Rom::Relation::Graph
    - Rom::Relation::Graph::Connector
    - Rom::Relation::Graph::Edge
    - Rom::Relation::Graph::Node::Name
    - Rom::Relation::Header
    - Rom::Relation::Mapper
    - Rom::Relation::Mapper::Builder
    - Rom::Relationship
    - Rom::Relationship::Iterator::Tuples
    - Rom::Relationship::ViaDefinition
    - Rom::Support::Graphviz
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
    - Rom::Attribute
    - Rom::Environment
    - Rom::Finalizer
    - Rom::Relation::Graph
    - Rom::Relation::Graph::Connector
    - Rom::Relation::Graph::Connector::Builder
    - Rom::Relation::Graph::Edge
    - Rom::Relation::Graph::Node::Name
    - Rom::Relation::Graph::Node::NameSet
    - Rom::Relation::Header
    - Rom::Relation::Mapper
    - Rom::Relation::Mapper::Builder
    - Rom::Relationship
    - Rom::Relationship::Iterator::Tuples
    - Rom::Relationship::ViaDefinition
    - Rom::Support::Graphviz
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
    - Rom::Attribute#self.build
    - Rom::Attribute::EmbeddedValue#finalize
    - Rom::AttributeSet#each
    - Rom::AttributeSet#merge
    - Rom::AttributeSet#remap
    - Rom::Environment#build
    - Rom::Environment#finalize
    - Rom::Finalizer#run
    - Rom::Finalizer::BaseRelationMappersFinalizer#register_base_relation
    - Rom::Finalizer::BaseRelationMappersFinalizer#registered_node
    - Rom::Finalizer::BaseRelationMappersFinalizer#registered_relation
    - Rom::Finalizer::BaseRelationMappersFinalizer#run
    - Rom::Finalizer::RelationshipMappersFinalizer#finalize_relationship_mappers
    - Rom::Finalizer::RelationshipMappersFinalizer#run
    - Rom::Mapper#each
    - Rom::Mapper#self.from
    - Rom::Mapper#self.map
    - Rom::Mapper::Builder#self.create
    - Rom::Mapper::Builder#self.define_for
    - Rom::Mapper::Builder#self.map_attribute
    - Rom::Mapper::Registry#each
    - Rom::Model#self.included
    - Rom::Options#add_accepted_option
    - Rom::Options#accept_options
    - Rom::Options#define_option_method
    - Rom::Query#each
    - Rom::Relation::Graph#freeze
    - Rom::Relation::Graph::Connector::Builder#add_edge
    - Rom::Relation::Graph::Connector::Builder#add_node
    - Rom::Relation::Graph::Edge#join_relation
    - Rom::Relation::Graph::Node#each
    - Rom::Relation::Graph::Node#join
    - Rom::Relation::Graph::Node#rename
    - Rom::Relation::Graph::Node::NameSet#each
    - Rom::Relation::Graph::Node::NameSet#rel_map
    - Rom::Relation::Header#each
    - Rom::Relation::Header#join
    - Rom::Relation::Header#self.build
    - Rom::Relation::Header::AttributeIndex#aliases
    - Rom::Relation::Header::AttributeIndex#renamed_relations
    - Rom::Relation::Header::AttributeIndex#self.initial_entries
    - Rom::Relation::Header::RelationIndex#aliases
    - Rom::Relation::Mapper#one
    - Rom::Relation::Mapper#order
    - Rom::Relation::Mapper#self.belongs_to
    - Rom::Relation::Mapper#self.from
    - Rom::Relation::Mapper#self.has
    - Rom::Relation::Mapper#self.key
    - Rom::Relation::Mapper::Builder#build
    - Rom::Relation::Mapper::RelationshipSet#each
    - Rom::Relationship#finalize
    - Rom::Relationship#finalize_join_definition
    - Rom::Relationship::Builder::Has#self.build
    - Rom::Relationship::Builder::Has#self.extract_min_max
    - Rom::Relationship::Iterator#each
    - Rom::Relationship::Iterator::Tuples#parent_base_tuple
    - Rom::Relationship::JoinDefinition#each
    - Rom::Relationship::ManyToMany#finalize
    - Rom::Relationship::OneToOne#finalize
    - Rom::Support::Graphviz#add_connectors
    - Rom::Support::Graphviz#add_edges
    - Rom::Support::Graphviz#add_nodes
    - Rom::Support::Graphviz#build
    - Rom::Utils#self.extract_options
    - Rom::Utils#self.extract_type
  max_statements: 2
UncommunicativeMethodName:
  enabled: true
  exclude:
    - 'n'  # typically used to denote infinity in DM code
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude:
    - Axiom::Adapter::Sqlite3
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude:
    - 'r' # typically used for 'relation' in blocks
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
    - Rom::Relation::Graph::Node::NameSet#via_relationship
    - Rom::Relation::Header#renamed_attribute_index
    - Rom::Relation::Header::AttributeIndex#new_attribute
    - Rom::Relation::Header::JoinStrategy#current_name
    - Rom::Relation::Header::JoinStrategy#joined_entries
    - Rom::Relation::Header::JoinStrategy#with_new_index_entries
  max_helper_calls: 0

